export type Severity = "Critical" | "High" | "Medium" | "Low" | "Good";

export type Anomaly = {
  title: string;
  description: string;
  severity: Severity;
};

export type RealityTraceStep = {
  step: string;
  confidence: number;
};

export type TruthScore = {
  risk: "HIGH" | "MEDIUM" | "LOW";
  category: string;
  impact: string;
  recommendation: string;
};

export type SourceMatch = {
  template: boolean | string;
  online: boolean;
  format: string;
};

export type AnalysisResult = {
  score: number;
  status: string;
  color: "red" | "yellow" | "green";
  anomalies: Anomaly[];
  realityTrace: RealityTraceStep[];
  truthScore: TruthScore;
  sourceMatch: SourceMatch;
  exampleImage?: string;
  exampleVideo?: string;
};

// Import example images
import fakeUpiImage from "../../assets/examples/fake-upi.png";
import fakeWhatsappImage from "../../assets/examples/fake-whatsapp.png";
import aiGeneratedImage from "../../assets/examples/ai-generated.jpeg";
import demoAIVideo from "../../assets/examples/DemoAIVideo.mp4";

export const exampleResults: Record<string, AnalysisResult> = {
  "fake-upi": {
    score: 23,
    status: "MANIPULATION DETECTED",
    color: "red",
    exampleImage: fakeUpiImage,
    anomalies: [
      {
        title: "Template Format Mismatch",
        description: "Layout doesn't match official UPI receipt structure",
        severity: "Critical"
      },
      {
        title: "Font Rendering Error",
        description: "Text font doesn't match standard UPI app fonts",
        severity: "High"
      },
      {
        title: "Missing Transaction Metadata",
        description: "Required transaction signature not found",
        severity: "Critical"
      },
      {
        title: "Timestamp Inconsistency",
        description: "Date/time format doesn't match UPI standards",
        severity: "Medium"
      }
    ],
    realityTrace: [
      { step: "Screenshot Captured", confidence: 95 },
      { step: "Edited in Image Editor", confidence: 89 },
      { step: "Text Modified", confidence: 92 },
      { step: "Re-exported as Image", confidence: 88 }
    ],
    truthScore: {
      risk: "HIGH",
      category: "Financial Fraud",
      impact: "If accepted as payment proof, this could enable fraud of ₹5,000-15,000",
      recommendation: "DO NOT accept this as valid payment confirmation. Verify through original UPI app."
    },
    sourceMatch: {
      template: false,
      online: false,
      format: "Failed 5/7 checks"
    }
  },
  "fake-whatsapp": {
    score: 31,
    status: "MANIPULATION DETECTED",
    color: "red",
    exampleImage: fakeWhatsappImage,
    anomalies: [
      {
        title: "UI Spacing Error",
        description: "Chat bubble spacing inconsistent with WhatsApp standards",
        severity: "High"
      },
      {
        title: "Timestamp Format Wrong",
        description: "Time display doesn't match WhatsApp format",
        severity: "High"
      },
      {
        title: "Font Mismatch",
        description: "Text font differs from official WhatsApp font",
        severity: "Medium"
      },
      {
        title: "Status Icon Incorrect",
        description: "Message status indicator doesn't match app design",
        severity: "Medium"
      }
    ],
    realityTrace: [
      { step: "Original Screenshot", confidence: 78 },
      { step: "Text Content Edited", confidence: 91 },
      { step: "Re-saved Multiple Times", confidence: 85 }
    ],
    truthScore: {
      risk: "MEDIUM",
      category: "Social Manipulation",
      impact: "Could be used to falsify conversations or spread misinformation",
      recommendation: "Request original message verification through WhatsApp app"
    },
    sourceMatch: {
      template: false,
      online: false,
      format: "Failed 4/7 checks"
    }
  },
  "ai-generated": {
    score: 12,
    status: "AI-GENERATED CONTENT",
    color: "red",
    exampleImage: aiGeneratedImage,
    anomalies: [
      {
        title: "Over-Smooth Skin Texture",
        description: "Slightly over-smooth skin texture indicating AI processing",
        severity: "High"
      },
      {
        title: "Symmetrical Facial Features",
        description: "Very symmetrical facial features beyond natural variation",
        severity: "High"
      },
      {
        title: "Hair Strand Inconsistencies",
        description: "Minor inconsistencies in hair strands near the ears",
        severity: "Medium"
      },
      {
        title: "Unnatural Eye Reflections",
        description: "Unnatural eye reflections that don't match the lighting",
        severity: "High"
      },
      {
        title: "Background Separation",
        description: "Soft but slightly blurred background separation",
        severity: "Medium"
      }
    ],
    realityTrace: [
      { step: "Generated by AI Model", confidence: 96 },
      { step: "Post-processed", confidence: 72 },
      { step: "Exported as Image", confidence: 94 }
    ],
    truthScore: {
      risk: "MEDIUM",
      category: "Synthetic Content / Misinformation",
      impact: "AI-generated content could be used to spread false information",
      recommendation: "Verify source and context before sharing or trusting"
    },
    sourceMatch: {
      template: "N/A",
      online: false,
      format: "No camera signature found"
    }
  },
  "ai-video-preview": {
    score: 18,
    status: "AI-GENERATED VIDEO",
    color: "red",
    exampleVideo: demoAIVideo,
    anomalies: [
      {
        title: "Temporal Coherence Breakdown",
        description: "Frame-to-frame inconsistencies detected. Facial features show unnatural transitions between frames, indicating AI-generated deep fake processing.",
        severity: "Critical"
      },
      {
        title: "Frame-Level Artifact Detection",
        description: "Multiple compression artifacts and unnatural pixel patterns detected across 47% of analyzed frames. These artifacts are consistent with AI video generation models.",
        severity: "High"
      },
      {
        title: "Motion-to-Texture Inconsistency",
        description: "Motion patterns do not align with texture details. Facial movements appear disconnected from underlying skin texture, a hallmark of deep fake generation.",
        severity: "Critical"
      },
      {
        title: "Unnatural Blinking Patterns",
        description: "Eye blinking frequency and pattern deviate from natural human behavior, indicating synthetic generation.",
        severity: "High"
      },
      {
        title: "Audio-Visual Synchronization Mismatch",
        description: "Lip movements do not perfectly synchronize with audio track, suggesting post-processing manipulation.",
        severity: "Medium"
      }
    ],
    realityTrace: [
      { step: "Generated by AI Model", confidence: 94 },
      { step: "Deep Fake Processing", confidence: 89 },
      { step: "Temporal Smoothing Applied", confidence: 76 },
      { step: "Exported as Video", confidence: 92 }
    ],
    truthScore: {
      risk: "HIGH",
      category: "Deep Fake Video / Misinformation",
      impact: "This AI-generated deep fake video could be used to spread false information, impersonate individuals, or create misleading content. High risk of misuse.",
      recommendation: "DO NOT trust this video as authentic. Verify through original sources and cross-reference with trusted channels before sharing or acting on its content."
    },
    sourceMatch: {
      template: "N/A",
      online: false,
      format: "No camera signature found - AI-generated"
    }
  }
};
